version: '3'
services:
  app-db:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_USER: docker_user
      POSTGRES_PASSWORD: docker_password
      POSTGRES_DB: docker_db
    ports:
      - "5432:5432"
    restart: always

  app:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    restart: always
    links:
      - app-db
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Djava.security.egd=file:/dev/./urandom -jar app.jar